### ISSUE TITLE
Unicode object names

### ISSUE THREAD

**Issue by ForNeVeR** [thliebig/AppCSXCAD#2]
Create new metal object, name it using Unicode (for example, "Стол 1").

AppCSXCAD will show it as "???? 1" in a property tree and will save it with ISO-8859-1 encoding into XML file (so, there will be something like `<Metal ID="2" Name="???? 1">`).

It also won't read properly formed UTF-8 XML file and display gibberish characters instead.

I think that AppCSXCAD should use Unicode for storing the object names and for saving the data.

(I am using Windows.)

**Comment by thliebig** [comment]
should be fixed in the CSXCAD and QCSXCAD libraries, nothing to do in AppCSXCAD.
Thanks for reporting.

**Comment by ForNeVeR** [comment]
Wow, you've already fixed that. Thanks a lot!
